name: Ejercicio 3

on: 
  pull_request:
    branches:
      - '*'

jobs:
  tareas:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Escaneo de codigo
        uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: pylint
